// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type Singer struct {
	Song   string
	Artist string
	Singer string
	Key    string
}

type Track struct {
	Name              string
	Artist            string
	Genre             []string
	DurationInSeconds int32
	Year              string
	Explicit          bool
	Bpm               int32
	OriginalKey       string
}

type Working struct {
	Name              string
	Artist            string
	Genre             []string
	DurationInSeconds int32
	Year              string
	Explicit          bool
	Bpm               int32
	OriginalKey       string
	Singer            sql.NullString
	SingerKey         sql.NullString
}
