// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

type Track struct {
	Name              string
	Artist            string
	Genre             []string
	DurationInSeconds int32
	Year              string
	Explicit          bool
	Bpm               int32
	Key               string
}
