version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: setlist_db
    environment:
      POSTGRES_DB: setlist_builder
      POSTGRES_USER: setlist_user
      POSTGRES_PASSWORD: setlist_pass
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U setlist_user -d setlist_builder"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
