FROM golang:1.24-alpine AS builder
ARG GOOS=linux
ARG GOARCH=amd64
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN apk add --no-cache build-base
RUN mkdir -p ./output
RUN CGO_ENABLED=1 GOOS=$GOOS GOARCH=$GOARCH go build -a -installsuffix cgo -o ./output/setlist_builder .
FROM scratch AS final
COPY --from=builder /app/output/setlist_builder /app/setlist_builder
CMD ["/app/setlist_builder"]
